name: research_env

channels:
  - conda-forge

dependencies:
  - python=3.8.6
  - pylint=2.6.0
  - pymongo=3.11.0
  - numpy=1.19.4
  - scipy=1.5.2
  - spacy=2.3.2
  - hdbscan=0.8.26
  - umap-learn=0.4.6
  - matplotlib=3.3.2
  - cmocean=2.0
  - scikit-learn=0.23.2
  - pandas=1.1.4
  - jupyterlab=2.2.9
  - gensim=3.8.3
  - nltk=3.5
  - networkx=2.5
  - squarify=0.4.3
